name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/taskhavensignupbg.png
    - assets/taskhaven_whitelogoicon.png
    - assets/taskhaven_greenlogoicon.png
    - assets/tempbg.png
    - assets/tempbg2.png
    - assets/avatarbase.png
    - assets/avatarcustomize/accessories/placeholderhat.png
    - assets/avatarcustomize/accessories/basicglasses.png
    - assets/avatarcustomize/accessories/basicshades.png
    - assets/avatarcustomize/accessories/flower1.png
    - assets/avatarcustomize/accessories/headphones1.png
    - assets/avatarcustomize/accessories/headphones2.png
    - assets/avatarcustomize/accessories/mushroomhat.png
    - assets/avatarcustomize/accessories/trafficcone.png
    - assets/avatarcustomize/accessories/witchhat.png
    - assets/avatarcustomize/shoes/basicshoes.png
    - assets/avatarcustomize/shoes/brownboots.png
    - assets/avatarcustomize/shoes/mushroomshoes.png
    - assets/avatarcustomize/shoes/shoeswithsocks.png
    - assets/avatarcustomize/pants/blackpants.png
    - assets/avatarcustomize/pants/jeans.png
    - assets/avatarcustomize/pants/whiteskirt.png
    - assets/avatarcustomize/shirts/blackcardigan.png
    - assets/avatarcustomize/shirts/bluelongsleevesshirt.png
    - assets/avatarcustomize/shirts/mushroomshirt.png
    - assets/avatarcustomize/shirts/pinkstarshirt.png
    - assets/avatarcustomize/shirts/redjacket.png
    - assets/avatarcustomize/shirts/whitepolo.png
    - assets/avatarcustomize/skin/skintone1.png
    - assets/avatarcustomize/skin/skintone2.png
    - assets/avatarcustomize/skin/skintone3.png
    - assets/avatarcustomize/skin/skintone4.png
    - assets/avatarcustomize/hair/femhair1.png
    - assets/avatarcustomize/hair/femhair2.png
    - assets/avatarcustomize/hair/femhair3.png
    - assets/avatarcustomize/hair/maschair1.png
    - assets/avatarcustomize/hair/maschair2.png
    - assets/avatarcustomize/hair/maschair3.png
    - assets/avatarcustomize/face/defaultface.png
    - assets/avatarcustomize/face/seriousface.png
    - assets/avatarcustomize/face/smileface.png
    - assets/avatarcustomize/face/smugface.png